ci(supernova): fixing not working supernova reports
gnolang/benchmarks pull request #19
Opened 2024-07-01 09:41 UTC by sw360cab

An attempt to fix the workflow for Supernova reporting.

The workflow was using:
* an outdated Gno startup procedure (`--skip-start`)
* an outdte binary of Supernova

Note: the matching of `Gno` container image and `Supernova` binary should be  automated or agreed somehow

2024-07-01 09:48 UTC, sw360cab commented
Actually this should be merged onto `main` branch too

2024-07-01 09:59 UTC, albttx commented on .github/workflows/supernova.yml
> +      - ci/supernova-fix
put back `ci/supernova`

2024-07-01 10:00 UTC, albttx commented on .github/workflows/supernova.yml
> +        image: ghcr.io/gnolang/gno/gnoland:0.1.0-nightly.20240620
update to `:master`

2024-07-01 10:01 UTC, sw360cab commented on .github/workflows/supernova.yml
> +      - ci/supernova-fix
Sorry for that, there is a missing push form local commit in the PR. I updated that

2024-07-01 10:03 UTC, albttx requested changes

2024-07-01 10:04 UTC, sw360cab commented on .github/workflows/supernova.yml
> +        image: ghcr.io/gnolang/gno/gnoland:0.1.0-nightly.20240620
latest/master, is not compatible with Supernova 1.2.0.

We have to deal with supernova/gno version matching in order to use `latest` supernova with `master` Gno image.
Otherwise this will always break if versions are not harcoded for both

2024-07-01 10:04 UTC, sw360cab commented on .github/workflows/supernova.yml
> +      # - name: Send report to slack \#gno-core-tech
missing push as for other

2024-07-01 10:06 UTC, sw360cab commented on .github/workflows/supernova.yml
> +          sleep 20
ok

2024-07-01 10:15 UTC, albttx commented on .github/workflows/supernova.yml
> +        image: ghcr.io/gnolang/gno/gnoland:0.1.0-nightly.20240620
in that case, we need to fix supernova fist, 
the goal to this benchmarks tool is to have a daily reports on performence with the latest branch of `gnoland`. So we could notice in case of improvement (or not) of the performences...

cc: @zivkovicmilos

2024-07-01 10:20 UTC, sw360cab commented on .github/workflows/supernova.yml
> +        image: ghcr.io/gnolang/gno/gnoland:0.1.0-nightly.20240620
I am working on fixing Supernova Gorelease meanwhile.

But actually the main concern I have is exactly the one you said @albttx .
If you check the latest PR of Supernova from `dependabot` (https://github.com/gnolang/supernova/pull/37)
it will align Gno with a nighly (0.1.0-nightly.20240627). I am not aware whether this corresponds to master or not.

2024-07-01 10:28 UTC, albttx commented on .github/workflows/supernova.yml
> +        image: ghcr.io/gnolang/gno/gnoland:0.1.0-nightly.20240620
`master` is the latest commit on master.

`0.1.0-nightly.*` is the daily commit took everyday at x., eg: `0.1.0-nightly.20240627` is `2024-06-27` (27 june 2024)

2024-07-23 17:20 UTC, zivkovicmilos commented on .github/workflows/supernova.yml
> +          sleep 20
............................why?

2024-08-14 15:51 UTC, sw360cab commented on .github/workflows/supernova.yml
> +        image: ghcr.io/gnolang/gno/gnoland:0.1.0-nightly.20240620
this has been solved by fixing supernova and gno releases

2024-08-14 15:54 UTC, merged

2024-10-18 09:46 UTC, sw360cab commented
Closes https://github.com/gnolang/gno/issues/2433